# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install -y graphviz
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run all Jupyter notebooks
      run: |
        cd en/practical1/
        papermill practical1.ipynb tmp.ipynb
        rm tmp.ipynb
        cd ../../ ; cd en/practical2/
        papermill practical2.ipynb tmp.ipynb
        rm tmp.ipynb
        cd ../../ ; cd en/Project/
        papermill Data.ipynb tmp.ipynb
        papermill Introduction.ipynb tmp.ipynb
        papermill Texts.ipynb  tmp.ipynb
        papermill miniproject.ipynb  tmp.ipynb
        rm tmp.ipynb
        cd ../../ ; cd fr/TP1/
        papermill tp1.ipynb tmp.ipynb
        rm tmp.ipynb
        cd ../../ ; cd fr/TP2/
        papermill tp2.ipynb tmp.ipynb
        rm tmp.ipynb
        cd ../../ ; cd fr/Projet/
        papermill Data.ipynb tmp.ipynb
        papermill Introduction.ipynb tmp.ipynb
        papermill Textes.ipynb  tmp.ipynb
        papermill miniprojet.ipynb  tmp.ipynb

